export const CATALOG_CATEGORIES: Record<
  string,
  { id: number; name: string; link: string }[]
> = {
  girls: [
    { id: 1, name: "Show all", link: "/girls" },
    { id: 2, name: "Dresses", link: "/" },
    { id: 3, name: "T-shirts", link: "/" },
    { id: 4, name: "Shirts", link: "/" },
    { id: 5, name: "Skirts", link: "/" },
    { id: 6, name: "Shorts", link: "/" },
    { id: 7, name: "Pants", link: "/" },
    { id: 8, name: "Jeans", link: "/" },
    { id: 9, name: "Sweaters", link: "/" },
    { id: 10, name: "Jackets", link: "/" },
    { id: 11, name: "Sale", link: "/" },
    { id: 12, name: "New collection", link: "/" },
  ],
  boys: [
    { id: 1, name: "Show all", link: "/boys" },
    { id: 2, name: "T-shirts/polo", link: "/" },
    { id: 4, name: "Shirts", link: "/" },
    { id: 7, name: "Pants", link: "/" },
    { id: 8, name: "Jeans", link: "/" },
    { id: 6, name: "Shorts", link: "/" },
    { id: 9, name: "Sweaters", link: "/" },
    { id: 10, name: "Jackets", link: "/" },
    { id: 11, name: "Sale", link: "/" },
    { id: 12, name: "New collection", link: "/" },
  ],
  woman: [
    { id: 1, name: "Show all", link: "/woman" },
    { id: 2, name: "Dresses", link: "/" },
    { id: 3, name: "Top/body", link: "/" },
    { id: 4, name: "T-shirts", link: "/" },
    { id: 5, name: "Shirts", link: "/" },
    { id: 6, name: "Skirts", link: "/" },
    { id: 8, name: "Pants", link: "/" },
    { id: 9, name: "Jeans", link: "/" },
    { id: 10, name: "Sweaters", link: "/" },
    { id: 11, name: "Jackets", link: "/" },
    { id: 12, name: "Accessories", link: "/" },
    { id: 13, name: "Sale", link: "/" },
    { id: 14, name: "New collection", link: "/" },
  ],
  man: [
    { id: 1, name: "Show all", link: "/man" },
    { id: 2, name: "Shirts", link: "/" },
    { id: 3, name: "T-shirts", link: "/" },
    { id: 4, name: "Pants", link: "/" },
    { id: 5, name: "Jeans", link: "/" },
    { id: 6, name: "Jackets", link: "/" },
    { id: 7, name: "Sweaters", link: "/" },
    { id: 8, name: "Accessories", link: "/" },
    { id: 9, name: "Sale", link: "/" },
    { id: 10, name: "New collection", link: "/" },
  ],
};
