export const CATALOG_CATEGORIES: Record<
  string,
  { id: number; name: string; isActive: boolean }[]
> = {
  girls: [
    { id: 1, name: "Show all", isActive: true },
    { id: 2, name: "Dresses", isActive: false },
    { id: 3, name: "T-shirts", isActive: false },
    { id: 4, name: "Shirts", isActive: false },
    { id: 5, name: "Skirts", isActive: false },
    { id: 6, name: "Shorts", isActive: false },
    { id: 7, name: "Pants", isActive: false },
    { id: 8, name: "Jeans", isActive: false },
    { id: 9, name: "Sweaters", isActive: false },
    { id: 10, name: "Jackets", isActive: false },
    { id: 11, name: "Sale", isActive: false },
    { id: 12, name: "New collection", isActive: false },
  ],
  boys: [
    { id: 1, name: "Show all", isActive: true },
    { id: 2, name: "T-shirts/polo", isActive: false },
    { id: 4, name: "Shirts", isActive: false },
    { id: 7, name: "Pants", isActive: false },
    { id: 8, name: "Jeans", isActive: false },
    { id: 6, name: "Shorts", isActive: false },
    { id: 9, name: "Sweaters", isActive: false },
    { id: 10, name: "Jackets", isActive: false },
    { id: 11, name: "Sale", isActive: false },
    { id: 12, name: "New collection", isActive: false },
  ],
  woman: [
    { id: 1, name: "Show all", isActive: true },
    { id: 2, name: "Dresses", isActive: false },
    { id: 3, name: "Top/body", isActive: false },
    { id: 4, name: "T-shirts", isActive: false },
    { id: 5, name: "Shirts", isActive: false },
    { id: 6, name: "Skirts", isActive: false },
    { id: 8, name: "Pants", isActive: false },
    { id: 9, name: "Jeans", isActive: false },
    { id: 10, name: "Sweaters", isActive: false },
    { id: 11, name: "Jackets", isActive: false },
    { id: 12, name: "Accessories", isActive: false },
    { id: 13, name: "Sale", isActive: false },
    { id: 14, name: "New collection", isActive: false },
  ],
  man: [
    { id: 1, name: "Show all", isActive: true },
    { id: 2, name: "Shirts", isActive: false },
    { id: 3, name: "T-shirts", isActive: false },
    { id: 4, name: "Pants", isActive: false },
    { id: 5, name: "Jeans", isActive: false },
    { id: 6, name: "Jackets", isActive: false },
    { id: 7, name: "Sweaters", isActive: false },
    { id: 8, name: "Accessories", isActive: false },
    { id: 9, name: "Sale", isActive: false },
    { id: 10, name: "New collection", isActive: false },
  ],
};
