# Generated by Django 5.1 on 2024-08-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creating')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of updating')),
                ('title', models.CharField(max_length=255, verbose_name='Product name')),
                ('description', models.TextField(blank=True, verbose_name='Description of product')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is the product visible in the catalog?')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
