import { ProductCardSize } from "@/components/ProductCard/types";
import { OrderProps } from "./components/OrderPreview/types";
import shirt from "@pages/Home/TemporaryCardImage/shirt.png";

export const testOrder: OrderProps[] = [
  {
    id: 1,
    status: "Delivered",
    price: 145,
    date: new Date(),
    items: [
      {
        id: 123,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
      {
        id: 34534,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
      {
        id: 163,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
      {
        id: 34574,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
      {
        id: 193,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
      {
        id: 349964,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
      {
        id: 359964,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
    ],
    country: "Ukraine",
    city: "Odesa",
    street: "Varnenskaya",
    homeNumber: 2,
    phoneNumber: "380636200000",
  },
  {
    id: 2,
    status: "Returned",
    price: 1045,
    date: new Date(),
    items: [
      {
        id: 567768,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
      {
        id: 76743,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
    ],
    country: "Ukraine",
    city: "Odesa",
    street: "Varnenskaya",
    homeNumber: 2,
    phoneNumber: "380636200000",
  },
  {
    id: 3,
    status: "Returned",
    price: 54,
    date: new Date(),
    items: [
      {
        id: 567768,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
      {
        id: 76743,
        title: "Men`s t-shirt",
        backgroundImage: shirt,
        size: ProductCardSize.Small,
        clothesSize: "S",
        color: "Black",
        price: 120,
      },
    ],
    country: "Ukraine",
    city: "Odesa",
    street: "Varnenskaya",
    homeNumber: 2,
    phoneNumber: "380636200000",
  },
];
